language: ruby
rvm:
  - 2.2.3
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rake spec
before_script:
  - psql -c 'create database pa_website_test_db;' -U postgres
  - bundle exec rake assets:precompile